export const USER_LOGIN_REQUEST ="USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCES ="USER_LOGIN_SUCCES";
export const USER_LOGIN_FAIL="USER_LOGIN_FAIL";
export const USER_LOGOUT="USER_LOGOUT";

export const USER_REGISTER_REQUEST ="USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCES ="USER_REGISTER_SUCCES";
export const USER_REGISTER_FAIL="USER_REGISTER_FAIL";

export const USER_DETAILS_REQUEST ="USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCES ="USER_DETAILS_SUCCES";
export const USER_DETAILS_FAIL="USER_DETAILS_FAIL";
export const USER_DETAILS_RESET="USER_DETAILS_RESET";

export const USER_UPDATED_PROFILE_REQUEST ="USER_UPDATED_PROFILE_REQUEST";
export const USER_UPDATED_PROFILE_SUCCES ="USER_UPDATED_PROFILE_SUCCES";
export const USER_UPDATED_PROFILE_FAIL="USER_UPDATED_PROFILE_FAIL";